### PR TITLE
Fix clonedigger in tox.

### PR DESCRIPTION
**Pull request by IvanMalison**

### CODE REVIEW

**Comment by hugovk** [comment]
clonedigger.sh is running but still causing an error:
```
lint runtests: commands[4] | ./clonedigger.sh
Parsing  pylast/__init__.py ... done
181 sequences
average sequence length: 6.425414
maximum sequence length: 127
Number of statements:  1163
Calculating size for each statement... done
Building statement hash... done
Number of different hash values:  213
Building patterns... 1000, 367 patterns were discovered
Choosing pattern for each statement... 1000, done
Finding similar sequences of statements...
-----------------------------------------
Warning: sequence of statements starting at pylast/__init__.py:168
consists of many similar statements.
It will be ignored. Use --force to override this restriction.
Please refer to http://clonedigger.sourceforge.net/documentation.html
-----------------------------------------
-----------------------------------------
Warning: sequence of statements starting at pylast/__init__.py:57
consists of many similar statements.
It will be ignored. Use --force to override this restriction.
Please refer to http://clonedigger.sourceforge.net/documentation.html
-----------------------------------------
592  sequences were found
Refining candidates... 81 clones were found
Removing dominated clones... -17 clones were removed
ERROR: InvocationError: '/home/travis/build/pylast/pylast/clonedigger.sh'
___________________________________ summary ____________________________________
ERROR:   lint: commands failed
```
https://travis-ci.org/pylast/pylast/jobs/46302746

`Removing dominated clones... -17 clones were removed` is the last line of output from clonedigger so perhaps this is a grep problem.

**Comment by IvanMalison** [comment]
i think its just that the exit code of clonedigger is not 0 because one of the grep commands returns no matches? So putting a ! before the grep command could work

**Comment by hugovk** [comment]
I couldn't get it to work with !, but piping to cat does.

**Comment by IvanMalison** [comment]
The problem with piping to cat is that it will always succeed even if there was output. I think we want it to report failure if the is output. Did you look at the latest in https://github.com/pylast/pylast/pull/117? I got it working with !, but it required putting it in a separate script

**Comment by IvanMalison** [comment]
I moived this into the ohter pull request.

**Comment by hugovk** [comment]
> The problem with piping to cat is that it will always succeed even if there was output. I think we want it to report failure if the is output. 

I'm not entirely convinced the build should fail if duplicates are found. Duplication should be avoided, but there may be cases where it's acceptable, and may be cases that the clonedigger tool is reporting something that's a duplicate that is actually fine.

Here's a [quick example from another project, using another duplication tool](https://scrutinizer-ci.com/g/hugovk/Pillow/indices/504318/duplications/36335140). These five classes are all subclasses of a BuiltinFilter and have the same structure with unique names and mostly unique filterargs, but they've been flagged as duplicates.

**Comment by IvanMalison** [comment]
agreed. I wasn't really sure what clonedigger did.

Whats the point of running clonedigger in continuous integration if the build can never fail? Maybe we can make it report a number about how much duplication there is.

In any case, I don't really care what is done with clonedigger. I feel like there is lower hanging fruit in this project at the moment.

Do you want me to change it to always exit 0?

**Comment by hugovk** [comment]
The CI doesn't just have to make pass/fail decisions about everything. It can also report on the current state, so you can run stuff on PRs that the submitter might not have done, and log the state of each build in history in case you ever want to go back and compare. See also Landscape stuff.

The stuff that was in the old `after_script ` step never failed any builds previously, just reported on them.

I also agree that this clonedigger isn't the most important thing, hence letting it not fail builds. Yes please to exit 0 (I saw you added it in the other PR).

**Comment by hugovk** [comment]
Fixed via #117.

**Pull request closed without merging**
