### PR TITLE
Drop support for Python 3.3

### PR DESCRIPTION
**Pull request by hugovk**
CPython 3.3 is no longer supported after September 29, 2017.

https://en.wikipedia.org/wiki/CPython#Version_history
https://www.python.org/dev/peps/pep-0398/

### CODE REVIEW

**Comment by hugovk** [comment]
Todo:

* [ ] Remove Python 3.3-specific code, for example from https://github.com/pylast/pylast/pull/178

**Comment by hugovk** [comment]
Removed the HTTP-only support for Python 3.3, which also drops support for Python <= 2.7.9.

**Comment by hugovk** [comment]
@simmel 2017-09 is here, time to remove the workarounds for Python 3.3 (and 2.7.9)! Please could you check this? Thanks!

**Comment by simmel** [comment]
According to https://docs.travis-ci.com/user/languages/python/#PyPy-Support `pypy3` is still `2.4.0` and that according to http://doc.pypy.org/en/latest/release-pypy3-2.4.0.html still is based on Python `3.2.5`.

Either we:
* use `pypy-5.3.1`, see Travis-CI docs above.
* leave the code to support a pypy3 version that old
* drop support for pypy3 (on Travis-CI)

I recommend using `pypy-5.3.1`.

LGTM!

**Comment by simmel** [comment]
Weird that it passed https://travis-ci.org/pylast/pylast/builds/276451255

Ah, looks like `pypy3` uses `PyPy 5.8.0-beta0` which is based on `Python 3.5.3`
https://travis-ci.org/pylast/pylast/jobs/276451261#L438

:shipit:

**Comment by hugovk** [comment]
Yep, Travis docs often lag behind what's actually available, and it can also depend on which Linux version is being used.

Thanks for checking, I'll merge this now and release it after September 29, 2017.

**Pull request merged**
