### PR TITLE
Bugfix for get_userloved and get_userplaycount resulting in an empty response from the server

### LINKED ISSUE #353: get_userplaycount and get_userloved issues
### What did you do?
Tried to search to see if a track was loved by a user and tried to get the number of times a track was played by a user

### What did you expect to happen?
To get the correct results

### What actually happened?
Always returns 0/False/None

### What versions are you using?

* OS: Ubuntu
* Python: 3.6.9
* pylast: 4.0.0

```python
import pylast

API_KEY = 'API KEY'
API_SECRET = 'API SECRET'
username = 'USERNAME'
password_hash = pylast.md5('PASSWORD')
network = pylast.LastFMNetwork(
    api_key=API_KEY,
    api_secret=API_SECRET,
    username=username,
    password_hash=password_hash
)

user = network.get_user(username)
print('Correctly gets user: ' + str(user))
print('Correctly gets current playing song: ' + str(user.get_now_playing()))

track = user.get_now_playing()
print(type(track))  # pylast.Track
print(track.get_userplaycount())  # Always 0
print(track.get_userloved())  # Always False
print(user.get_loved_tracks())  # Returns results.

print("--------------")

print("Recent Tracks: (All should be played at least once)")
for pt in user.get_recent_tracks():
    t = pt.track
    print(t)
    print(t.get_userplaycount())
    print(t.get_userloved())
    print()

print("------------------")

print("Loved tracks: (All should be userloved)")
for lt in user.get_loved_tracks(cacheable=False):
    t = lt.track
    print(t)
    print(t.get_userplaycount())
    print(t.get_userloved())
    print()

```

### PR DESCRIPTION
**Pull request by kvanzuijlen**
Fixes #353 

Changes proposed in this pull request:

 * Default username context of track to the current user if not set
 * LastFM API seems to have problems interpreting the 'username' parameter when it's included in the post body. Since it's only used to retrieve the context of a track/album/artist (afaik) I would propose this as a temporary solution only until LastFM manages to fix this on their end.

Used the following piece of code to reproduce the problem:
```python
import pylast

# You have to have your own unique two values for API_KEY and API_SECRET
# Obtain yours from https://www.last.fm/api/account/create for Last.fm
API_KEY = "***"
API_SECRET = "***"

# In order to perform a write operation you need to authenticate yourself
username = "***"
password_hash = "***"

network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET,
                               username=username, password_hash=password_hash)
track = network.get_authenticated_user().get_recent_tracks(limit=1)[0]
playcount = track.track.get_userplaycount()
print(playcount)
```
Which resulted in:
image
(32 being my play count for that track)

Also reproduced it with Postman:
**Username in post body**
image

**Username as query string**
image

I ran all tests locally and they all passed:
image

### CODE REVIEW

**Comment by falsovsky** [comment]
This needs to be merged.

**Comment by hugovk** [comment]
@kvanzuijlen Hi! This PR is a draft, is it ready for review?

(And please could you add a descriptive PR title? It'll be used in the release notes.)

**Comment by kvanzuijlen** [comment]
@hugovk Yes, I think it is. If you need me to change anything, please let me know. I'll have some time coming weeks to make changes.

**Comment by hugovk** [comment]
> * LastFM API seems to have problems interpreting the 'username' parameter when it's included in the post body. Since it's only used to retrieve the context of a track/album/artist (afaik) I would propose this as a temporary solution only until LastFM manages to fix this on their end.

Do we have any idea how long this temporary solution will be needed, or how long it'll take Last.fm to fix it on their side? Has it even been reported to them? If now, please report it. Thanks!

**Comment by kvanzuijlen** [comment]
> > * LastFM API seems to have problems interpreting the 'username' parameter when it's included in the post body. Since it's only used to retrieve the context of a track/album/artist (afaik) I would propose this as a temporary solution only until LastFM manages to fix this on their end.
> 
> Do we have any idea how long this temporary solution will be needed, or how long it'll take Last.fm to fix it on their side? Has it even been reported to them? If now, please report it. Thanks!

I have reported it to them, haven't heard back anything though.

**Comment by hugovk** [comment]
Thanks, did you report on their forum or another way?

**Comment by falsovsky** [comment]
Please merge this @hugovk, this library has been broken for years because of this.
As we see Last.FM wont change its code, so its better to adapt to it.

**Comment by kvanzuijlen** [comment]
Hi @hugovk,

I reported the issue via their support forum as I'm not aware of any other way to contact them.

https://support.last.fm/t/lastfm-api-track-artist-album-getinfo/38509/3

If you know any other way, please let me know.

**Pull request merged**
