### PR TITLE
replaced opensearch: as empty str

### PR DESCRIPTION
**Pull request by yanggao1119**
temparory fix for minidom.parsestring error related to opensearch namespace.

### CODE REVIEW

**Comment by hugovk** [comment]
That works with your example code. I've merged this into its own branch at https://github.com/pylast/pylast/pull/154.

If the problems at Last.fm carry on for even longer, I may merge this into the main branch with more testing. 

Thanks!

**Comment by yanggao1119** [comment]
lastfm api seems to be working for xml results?

yang

Yang Gao
213.618.2259 | yanggao1119@gmail.com

On Tue, Sep 22, 2015 at 6:50 AM, Hugo van Kemenade <notifications@github.com

**Comment by hugovk** [comment]
The Last.fm API is still broken (http://www.last.fm/api/show/artist.search) but your example code from https://github.com/pylast/pylast/issues/152 works with this pull request:

```python
import pylast

api_key = API_KEY
network = pylast.LastFMNetwork(api_key = api_key)

artistsearch_obj = network.search_for_artist("Coldplay")
result = artistsearch_obj.get_next_page()
```

**Comment by hugovk** [comment]
The Last.fm API is **still** broken, nearly six months later, and aren't in any rush to fix it, so let's release this workaround.

Resolves #152.

Thanks for the contribution!

**Pull request merged**
