### PR TITLE
This adds the limit parameter to track.get_similar()

### PR DESCRIPTION
**Pull request by leomos**
I needed this for my own project, I hope it's useful.
I'm sorry that the date changed too, if needed I'll make another PR with the date left at 2017.

### CODE REVIEW

**Comment by leomos** [comment]
Yes sure, I'll work on it.

**Comment by hugovk** [comment]
Just run "flake8 ." locally should be enough. Don't worry too much about the non-lint build jobs falling.

**Comment by leomos** [comment]
All right I think I fixed everything, flake8 is giving no more errors, should I open another PR or edit the files here?

**Comment by hugovk** [comment]
Edit here please.

**Comment by hugovk** [comment]
Thanks!

**Pull request merged**
