### PR TITLE
Adding support for tag.getTopTracks

### PR DESCRIPTION
**Pull request by skillachie**
Adding support for http://www.last.fm/api/show/tag.getTopTracks API.
--added method
--added test

### CODE REVIEW

**Comment by skillachie** [comment]
PS. The build was failing before https://travis-ci.org/pylast/pylast/builds

**Comment by hugovk** [comment]
@skillachie Yep, the build is a bit flakey because it makes lots of network calls to Last.fm which sometime fail. They should be mocked or retried on failure.

Thanks for the PR, I'll check it in more detail later.

**Comment by hugovk** [comment]
@skillachie Can't you already do this with `Tag.get_top_tracks()`?

For example:

```python
>>> tag = network.get_tag("happy")
>>> tracks = tag.get_top_tracks()
>>> tracks[0]
TopItem(item=pylast.Track(u'Pharrell Williams', u'Happy', pylast.LastFMNetwork(...)), weight=0)
```

**Comment by skillachie** [comment]
@hugovk Indeed I must have missed it while looking in the code to find the correct method to use .  You should be able to close this pull request.

Thanks for the nice library. If i had time I would help you with the documentation to prevent the above

**Comment by hugovk** [comment]
No problem, I appreciate the effort making the PR, especially with a test.

**Pull request closed without merging**
