### PR TITLE
Improve handling of error responses from the API

### PR DESCRIPTION
**Pull request by spiritualized**
Fixes #

Changes proposed in this pull request:

 * Raise a WSError if the API response contains a non-200 code, instead of failing to interpret the body and raising a MalformedResponseError

### CODE REVIEW

**Comment by spiritualized** [comment]
@hugovk, will you accept this change?

I'm not getting the test failures locally, perhaps there's a problem with the configured password or API key.

**Comment by hugovk** [comment]
Yeah, tests fail for PRs due to https://github.com/pylast/pylast/issues/171.

I was wondering, not every non-200 status is an error. For example, could there be 3xx redirect statuses? How about other statuses?

**Comment by spiritualized** [comment]
Good point. Altered the check to only catch relevant 5xx errors.

**Comment by hugovk** [comment]
Thank you!

**Pull request merged**
