### PR TITLE
Migrate from setuptools + setuptools_scm to hatchling + hatch-vcs

### PR DESCRIPTION
**Pull request by hugovk**
Changes proposed in this pull request:

 * Migrate from setuptools to hatchling
 * And setuptools_scm to hatch-vcs
 * With help from https://github.com/abravalheri/ini2toml/ and https://github.com/abravalheri/validate-pyproject/

### CODE REVIEW

**Comment by djmattyg007** [comment]
I’m curious what you found appealing about hatchling that made it worth using over something more well known like poetry.

**Comment by djmattyg007** [comment]
Does renovatebot support hatchling?

**Comment by hugovk** [comment]
> I’m curious what you found appealing about hatchling that made it worth using over something more well known like poetry.

Well first of all, I'd like to move away from setuptools which is getting a bit old (or ["`setuptools` is a _hot mess_ of legacy code"](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) :). It is being modernised, but there may be some disruption in the process (e.g. https://github.com/pypa/setuptools/issues/3532).

Hatchling is standards compliant, and specifically built based on the new packaging standards for build backends ([PEP 517](https://peps.python.org/pep-0517/)/[PEP 660](https://peps.python.org/pep-0660/)) and the format for metadata declaration ([PEP 621](https://peps.python.org/pep-0621/)/[PEP 631](https://peps.python.org/pep-0631/)).

Also I haven't used Poetry much, so it doesn't gain much familiarity points.

And I've seen a lot of interest and other projects moving over, here's a few: https://hatch.pypa.io/latest/users/ (It's also the default option in this PyPA tutorial https://packaging.python.org/en/latest/tutorials/packaging-projects/.)

> Does renovatebot support hatchling?

No, renovatebot doesn't support PEP 621 / hatchling: https://github.com/renovatebot/renovate/issues/10187 But it doesn't matter as we're not pinning any dependencies there (as libraries shouldn't). We're only using it for GitHub Actions.

**Comment by ofek** [comment]
Any update on this?

**Comment by hugovk** [comment]
@djmattyg007 Do you have any further questions or concerns?

**Comment by djmattyg007** [comment]
Nope. I was just curious.

**Comment by hugovk** [comment]
Good stuff, let's get this merged! 🚀

**Pull request merged**
