### PR TITLE
Document how to authenticate with a session key

### LINKED ISSUE #417: Oauth authentication
### What did you do?
I want to use this library in an application which will authenticate the user, then allow them to do scrobbling based on that authentication. Your examples all seem to involve hardcoding (or potentially storing in a database) a user's password. 

### What did you expect to happen?
OAuth was made for this use case, and I can't seem to find any support for oauthing users in this library

### What actually happened?
Right now I seem to be stuck hardcoding an individual user or asking the user for their password.

Am I missing something in the docs, or is Oauth not implemented in this library?

### PR DESCRIPTION
**Pull request by ndm13**
Describe authentication with OAuth token

Fixes #417

### CODE REVIEW

**Comment by adammpkins** [comment]
+1 for this PR

**Comment by hugovk** [comment]
Thanks for the PR!

I've made an edit to put the alternatives in their own code blocks, to try and make it a bit clearer. How does this look?

https://github.com/ndm13/pylast/blob/patch-1/README.md#getting-started

**Comment by ndm13** [comment]
I like splitting it up, but I think either the import and API info should be a separate block or it should be in both blocks. I'm picturing people copying and pasting and being annoyed.

**Comment by hugovk** [comment]
Thank you!

**Pull request merged**
