### PR TITLE
Add missing limit parameter for track.getSimilar

### LINKED ISSUE #249: track.getSimilar is missing the limit parameter
### What did you do?
Try to use the limit parameter for track.getSimilar

### What did you expect to happen?
The query to work.

### What actually happened?
The function call fails because it doesn't have the limit parameter.

### What versions of OS, Python and pylast are you using?
Python 3.6, OS/X 10.12, pylast 2.1.0 and master

I have a PR for this ready to submit.

### PR DESCRIPTION
**Pull request by redshodan**
Fixes #249 

Changes proposed in this pull request:

 * Add the limit parameter to the track.getSimilar query

### CODE REVIEW

**Comment by redshodan** [comment]
The build failed with "Invalid API key - You must be granted a valid key by last.fm". I guess something needs updating?

**Comment by hugovk** [comment]
See https://github.com/pylast/pylast/issues/171 for why it failed. I'll test locally.

Please could you add unit tests? Something like https://github.com/pylast/pylast/blob/e0f52ac27d7b2dde619a8863e5bf9bea8ab07856/tests/test_pylast_user.py#L136-L145

**Comment by redshodan** [comment]
Added. That worked for me, however these two other tests failed. I'm wasn't terribly sure what to put for the lower limit of the tests with no limit, but 23 worked for this Cher song.

TestPyLastAlbum.test_album_in_artist_tracks
TestPyLastUser.test_album_tracks

**Comment by hugovk** [comment]
Thanks, merging!

`test_album_in_artist_tracks` passes for me, but `test_album_tracks` also fails on master, so I'll sort those later.

**Pull request merged**
